- name: Install package and notify Slack
  hosts: local
  connection: local
  become: yes
  vars:
    slack_webhook: "https://hooks.slack.com/services/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"

  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      notify: Notify Slack on install

  handlers:
    # - name: Notify Slack on install
    #   ansible.builtin.uri:
    #     url: "{{ slack_webhook }}"
    #     method: POST
    #     headers:
    #       Content-Type: "application/json"
    #     body: >
    #       {
    #         "text": ":white_check_mark: *Nginx installed successfully* on {{ inventory_hostname }}"
    #       }
    #     body_format: json
    # - name: Notify Slack on install
    #   uri:
    #     url: "https://hooks.slack.com/services/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"
    #     method: POST
    #     headers:
    #       Content-Type: "application/json"
    #     body: |
    #       {
    #         "text": "✅ Nginx was successfully installed on {{ inventory_hostname }}!"
    #       }
    #     body_format: json
    #   delegate_to: localhost

    - name: Notify Slack on install
      uri:
        url: "https://hooks.slack.com/services/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"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "text": "✅ Nginx was successfully installed on {{ inventory_hostname }}!"
          }
        body_format: json
      delegate_to: localhost