- name: Install package and notify Slack
  hosts: local
  connection: local
  become: yes
  vars:
    slack_webhook: "https://hooks.slack.com/services/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"

  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      notify: Notify Slack on install

  handlers:
    - name: Notify Slack on install
      ansible.builtin.uri:
        url: "{{ slack_webhook }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {
            "text": ":white_check_mark: *Nginx installed successfully* on {{ inventory_hostname }}"
          }
        body_format: json
