- name: Install packages using loop
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install the servers
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - httpd
    - git
    - postfix
    - nodejs