- name: install nginx package
  hosts: all
  become: yes
  tasks:
  # - name: Package nginx installation
  #   ansible.builtin.package:
  #     name: nginx
  #     state: present
  # - name: Start the service
  #   ansible.builtin.service:
  #     name: nginx
  #     state: started
  #     enabled: yes
  - name: Package Apache installation
    ansible.builtin.package:
      name: httpd
      state: present
  - name: Package Apache installation
    ansible.builtin.package:
      name: httpd
      state: absent