- name: Function or filter in ansible to manipulate data
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
      msg: "I am {{ ENG | default ('AWS DevOps') }} engineer"

  - name: convert upper to lower
    vars:
      ENG: "AWS DEVOPS"
    ansible.builtin.debug:
      msg: "I am {{ ENG | lower }} engineer"

  - name: convert lower to upper
    vars:
      ENG: "azure developer"
    ansible.builtin.debug:
      msg: "I am {{ ENG | upper }} engineer"

  - name: Print unique numbers only
    vars:
      ENG: [1, 2, 2, 3, 22, 4, 22, 3]
    ansible.builtin.debug:
      msg: "Unique numbers are: {{ ENG | unique }}"

  - name: Max and Min numbers
    vars:
      ENG: [1, 2, 2, 3, 22, 4, 22, 3]
    ansible.builtin.debug:
      msg: "Min: {{ ENG | min }}, Max: {{ ENG | max }}"
    
  #dict to items
  - name: covert dict to items
    vars:
      devops:
        user: "Durga"
        age: 20
        YOE: 3
    ansible.builtin.debug:
      msg: "User deatils are: {{ devops | dict2items }}"
  
  #Convert Map to dict
  - name: Map to Dictionary
    vars:
      devops:
      - key: "user"
        value: "Durga"
      - key: "age"
        value: 20
      - key: "YOE"
        value: 3
    ansible.builtin.debug:
      msg: "The user deatils are: {{ devops | items2dict }} "
  #To test if a string is a valid IP address:
  - name: test given IP is valid or not
    vars:
      my_var: "2.2.20./24"
    ansible.builtin.debug:
      msg: "Ip address is: {{ my_var | ansible.utils.ipv4 }}" #ansible.utils.ipv6