- name: Checkk Shell vs Command 
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Simple command 
    ansible.builtin.command: ls -ltr

  - name: Shell 
    ansible.builtin.shell: ps -ef | grep ssh > /tmp/prasad.txt
  