- name: check the user
  hosts: local
  become: yes #need root to create user or need executr permision
  connection: local
  tasks:
  - name: craete the user 'expense'
    ansible.builtin.user:
      name: expense
      state: present