- name: See ansible facts
  hosts: local
  become: yes #need root to create user or need executr permision
  connection: local
  tasks:
  - name: checking ansible facts
    ansible.builtin.debug:
      msg: "facts are {{ ansible_facts }}"
  - name: install pacakges for Redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    # when: ansible_os_family == "RedHat"
    when: ansible_distribution == "RedHat"
  - name: install pacakges for debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_distribution == "Debian"
    # when: ansible_os_family == "Debian"
  - name: install pacakges for ubuntu
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_distribution == "Ubuntu"
    # when: ansible_os_family == "Ubuntu"