- name: See ansible facts
  hosts: local
  become: yes #need root to create user or need executr permision
  connection: local
  tasks:
  - name: checking ansible facts
    ansible.builtin.debug:
      msg: "facts are {{ ansible_facts }}"